version: '3.8'

services:
  web:
    build: ./.docker/apache
    container_name: todo.apache
    ports:
      - 8081:80
    privileged: true
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    container_name: todo.db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: todo_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
  mail:
    container_name: todo.mail
    image: mailhog/mailhog
    ports:
      - 8025:8025
